### ISSUE TITLE
No remote connection over HTTP?

### ISSUE THREAD

**Issue by lnwdr** [nolanlawson/worker-pouch#6] opened 2016-01-19 14:55 UTC
Hi, I've been trying to setup my PouchDB ,syncing with a remote CouchDB, inside a worker using this plugin.

After some digging around, I found that the function for creating a HTTP connected Pouch inside the worker is actually never called. The `makePouchCreator` function is always called with an empty `options` object:

<https://github.com/nolanlawson/worker-pouch/blob/master/lib/worker/index.js#L240-L241>

```js
var options = {};
var pouchCreator = makePouchCreator(options);
```

This leads to the `createHttpPouch` function never being called:

<https://github.com/nolanlawson/worker-pouch/blob/master/lib/worker/make-pouch-creator.js#L33-L39>
```js
function makePouchCreator(options) {
  if (options.remoteUrl) {
    return createHttpPouch(options);
  }
  if (!options.pouchCreator) {
    return createLocalPouch;
  }

  // …
}
```

So, as I see it, PouchDB sync with another DB over HTTP doesn't work at all when using `worker-pouch`.

Or am I missing something?

**Comment by nolanlawson** [comment] 2016-01-22 18:44
Yes, you're right, looks like this is something that I failed to actually test. Unfortunately, the way the code is currently written, you would have to use a workaround:

```js
var local = new PouchDB('local', {adapter: 'worker'});
var remote = new PouchDB('http://wherver');
local.sync(remote, ...);
```

Rather than:

```js
var local = new PouchDB('local', {adapter: 'worker'});
local.sync(remote, 'http://wherver');
```

**Comment by nolanlawson** [comment] 2016-01-22 18:45
I agree that this is something that ought to be fixed, and I will happily accept pull requests. :)

**Comment by ronyrun** [comment] 2016-02-16 17:27
I tried 

```node
var local = new PouchDB('local', {adapter: 'worker'});
var remote = new PouchDB('http://wherever');
local.sync(remote, ...);
```

and it doesn't either.

I'll continue the tests.

**Comment by nolanlawson** [comment] 2016-02-16 17:37
This ought to be fixed now. Can you please provide a reproducible test case?

**Comment by nolanlawson** [comment] 2016-02-16 17:43
This is working for me now, using both the string style and the `new PouchDB()` style: http://bl.ocks.org/nolanlawson/bd2079b598e54eb7ef9c

Closing this issue. Please reopen if this is still a problem.

**Closed by nolanlawson** 2016-02-16 17:43 UTC
